name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.11']
        include:
          - os: windows-latest
            asset_name: pdf_unlocker_windows.exe
            asset_content_type: application/vnd.microsoft.portable-executable
          - os: macos-latest
            asset_name: pdf_unlocker_macos
            asset_content_type: application/x-mach-binary
          - os: ubuntu-latest
            asset_name: pdf_unlocker_linux
            asset_content_type: application/x-executable

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pikepdf tkinterdnd2 pyinstaller

    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --windowed --hidden-import=pikepdf --add-data "C:\hostedtoolcache\windows\Python\${{ matrix.python-version }}.*\x64\Lib\site-packages\tkinterdnd2\tkdnd;tkinterdnd2/tkdnd" .\unlock.py

    - name: Build with PyInstaller (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --windowed --hidden-import=pikepdf --add-data "/Users/runner/hostedtoolcache/Python/${{ matrix.python-version }}*/x64/lib/python${{ matrix.python-version }}/site-packages/tkinterdnd2/tkdnd:tkinterdnd2/tkdnd" ./unlock.py

    - name: Build with PyInstaller (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --onefile --windowed --hidden-import=pikepdf --add-data "/opt/hostedtoolcache/Python/${{ matrix.python-version }}*/x64/lib/python${{ matrix.python-version }}/site-packages/tkinterdnd2/tkdnd:tkinterdnd2/tkdnd" ./unlock.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
